site_name: NIHPC Documentation
nav:
    - 'index.md'
    - 'Kelvin2 Overview.md'
    - 'Connecting to Kelvin2.md'
    - 'Getting Started.md'
    - 'Modules & Jobscripts.md'
    - 'Job Submission.md'
    - 'Applications.md'
    - 'Compilers.md'
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
  - scheme: slates
    primary: red

    extra:
    social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/home

markdown_extensions:
  - pymdownx.betterem
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
